spring:
  jpa:
#    show-sql: true
    hibernate:
      #Switching
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    database: mysql

  profiles:
    include: secret